---
- name: Demo Playbook
  hosts: webservers
  become: yes
  become_user: root
  vars_files:
    - vars/default.yml
  tasks:
    - name: Update and upgrade apt packages
      apt: 
        upgrade: yes
        update_cache: yes
        cache_valid_time: 3600

    - name: Install apache2
      apt:  
        name: apache2
        state: latest

    - name: Copy index.html file
      copy:
        src: "files/index.html"
        dest: "/var/www/html/index.html"

    - name: Start apache2
      service:
        name: apache2
        state: started
      